// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeR1pVZ2S7sPR6FK99kn05ueU4__Z5ajM',
    appId: '1:215078240772:web:ea0b47bb779e656344ab51',
    messagingSenderId: '215078240772',
    projectId: 'skhickens-app',
    authDomain: 'skhickens-app.firebaseapp.com',
    storageBucket: 'skhickens-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1lBEHrta7ZResdRk9qY2QppZKTUp9TQs',
    appId: '1:215078240772:android:48b49b7d2562600244ab51',
    messagingSenderId: '215078240772',
    projectId: 'skhickens-app',
    storageBucket: 'skhickens-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfG_3z_vlB_44D0abJFq51hZXwrC4WyfM',
    appId: '1:215078240772:ios:3a4b63bb005d224844ab51',
    messagingSenderId: '215078240772',
    projectId: 'skhickens-app',
    storageBucket: 'skhickens-app.appspot.com',
    iosBundleId: 'com.example.skhickensApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfG_3z_vlB_44D0abJFq51hZXwrC4WyfM',
    appId: '1:215078240772:ios:4feedac223461f5944ab51',
    messagingSenderId: '215078240772',
    projectId: 'skhickens-app',
    storageBucket: 'skhickens-app.appspot.com',
    iosBundleId: 'com.example.skhickensApp.RunnerTests',
  );
}
